name: "Registry release listener"
description: "Listens for new releases on registry packages"
inputs:
  token:
    description: "Github Access Token"
    required: true
  name:
    description: "Name of package"
    required: true
  version:
    description: "Version of release"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: "Get package registry data"
      uses: actions/checkout@v3
      with:
        repository: swift-nav/package-registry
        token: ${{ inputs.token }}
        clean: false
        path: ''
        ref: ''

    - name: "Ensures release is not linked"
      shell: bash
      run: |
        if cat data/${{ inputs.name }} | grep "\"version\":\"${{ inputs.version }}\""; then
          exit 1
        fi

    - name: "Modify data to link release"
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
      run: |
        ls
        sh link_release.sh

    - name: "Create pull request from changes"
      shell: bash
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/swift-nav/package-registry/pulls \
          -f title='Amazing new feature'
         -f body='Please pull these awesome changes in!'
         -f head='superbot:${{ inputs.name }}-${{ inputs.version }}'
         -f base='master'