name: "Registry release listener"
description: "Listens for new releases on registry packages"
inputs:
  token:
    description: "Github Access Token"
    required: true
  name:
    description: "Name of package"
    required: true
  version:
    description: "Version of release"
    required: true
runs:
  using: composite
  steps:
    - name: "Get package registry data"
      uses: actions/checkout@v3
      with:
        repository: swift-nav/package-registry
        token: ${{ inputs.token }}
        clean: 'false'
        path: 'package-registry'

    # using this because clean: false isn't working
    - name: "Extract cloned repo"
      shell: bash
      run: |
        find .
        mv -v ./package-registry/* .
        rm -r ./package-registry

    - name: "Ensures release is not linked"
      shell: bash
      run: |
        if cat data/${{ inputs.name }} | grep "\"version\":\"${{ inputs.version }}\""; then
          exit 1
        fi

    - name: "Modify data to link release"
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
      run: |
        ls
        bash link_release.sh

    - name: "Create pull request from changes"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        git switch -c "coolbot/update"
        git add .
        git commit -m "Updating release for ${{ inputs.name }}-${{ inputs.version}}"
        gh pr create --title "The bug is fixed" --body "Everything works again"