name: "Registry release listener"
description: "Listens for new releases on registry packages"
inputs:
  token:
    description: "Github Access Token"
    required: true

  # not sure why defaults not working...
  gh-name:
    description: "Github account name"
    required: true
    default: "swiftnav-travis"
  gh-email:
    description: "Github account email"
    required: true
    default: "swiftnav-travis@swift-nav.com"

runs:
  using: composite
  steps:
    # quick fix under path package-registry as clean doesn't work.
    - name: "Get package registry data"
      uses: actions/checkout@v3
      with:
        repository: swift-nav/package-registry
        token: ${{ inputs.token }}
        path: 'package-registry'

    - name: "Move script into package-registry"
      shell: bash
      run: mv -v link_release.sh template.json package-registry

    - name: "Store name and version env vars"
      shell: bash
      run: |
        echo "NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "Stored ${{ env.NAME }} and ${{ env.VERSION }}"

    - name: "Ensures release is not linked"
      shell: bash
      working-directory: package-registry
      run: |
        if cat data/${{ env.NAME }} | grep "\"version\":\"${{ env.VERSION }}\""; then
          exit 1
        fi

    - name: "Modify data to link release"
      shell: bash
      working-directory: package-registry
      env:
        NAME: ${{ env.NAME }}
        VERSION: ${{ env.VERSION }}
      run: bash link_release.sh

    - name: "Create pull request from changes"
      shell: bash
      working-directory: package-registry
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        rm link_release.sh template.json
        git config --global user.email "swiftnav-travis@swift-nav.com"
        git config --global user.name "swiftnav-travis"
        git switch -c "coolbot/update-${{ env.NAME }}-${{ env.VERSION }}"
        git add .
        git commit -m "Updating release for ${{ env.NAME }}-${{ env.VERSION }}"
        git push --set-upstream origin coolbot/update-${{ env.NAME }}-${{ env.VERSION }} -f
        gh pr create \
          --title "Release for ${{ env.NAME }}-${{ env.VERSION }}" \
          --body "Automated registry sync for ${{ env.NAME }} ${{ env.VERSION }}" \
          --reviewer adrian-kong,isaactorz,silverjam